# Project metadata for slurm-factory
name: "slurm-factory"
version: "1.0.0"
description: "Modern HPC cluster builder using LXD containers and Spack package manager"
repository: "https://github.com/vantagecompute/slurm-factory"
documentation: "https://vantagecompute.github.io/slurm-factory"
license: "Apache 2.0"
python_version: ">=3.11"
updated: "2025-08-11"

# Supported Slurm versions
slurm_versions:
  - "25.05"
  - "24.11" 
  - "24.05"
  - "23.11"
  - "23.02"

# Key technologies
technologies:
  - "Python 3.11+"
  - "LXD Containers"
  - "Spack Package Manager"
  - "UV Package Manager"
  - "Typer CLI Framework"
  - "Environment Modules/Lmod"

# Package features
features:
  - "Automated Slurm builds"
  - "CPU and GPU optimized packages"
  - "Module system integration"
  - "Portable deployment packages"
  - "Multi-version support"
  - "HPC optimized configurations"
